name: cowsay

on:
    push:
        branches: main
jobs:
    cowsay_lab:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: list files
              run: ls -ltra

            - name: Run shell script
              run: |
                chmod +x Cowsay.sh
                ./Cowsay.sh
            

            - name: Upload the dragon file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-artwork-file
                path: dragon.txt