name: cowsay

on:
    push:
        branches: main
jobs:
    first_lab:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: list files
              run: ls -ltra

            - name: run shell script
              run: |
               chmod +x Cowsay.sh
               ./Cowsay.sh

            - run: mkdir -p path/to/artifact
            
            - uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: dragon.txt